### ISSUE TITLE
스트라티스 소스를 비주얼스튜디오에서 어떻게 오픈해야하나요??

### ISSUE THREAD

**Issue by baboqoo** [devjin0617/coin-news#2]
안녕하세요..  c# 아주 극초보 개발자입니다..

질문 내용대로 비주얼스튜디오에서 소스 코드를 오픈하고 싶은데요..
제가 쓰고 있는 vs2015 에서는 오픈이 되지 않아서요..
어떻게 하면 열어볼 수 있는지 궁금합니다..
또한 개발 환경은 어떻게 맞춰야 수월할지도 궁금합니다!!

알려주시면 감사하겠습니다..

**Comment by devjin0617** [comment]
안녕하세요! 제가 답변을 늦게 확인했네요

저는 C#개발을 하고 있지는 않지만 스트라티스플랫폼에 관해 관심도는 높은 편입니다.

스트라티스에서는 C#으로 진행되고 있는 프로젝트가 많이 있습니다. 그 중에서 메인으로 진행되고 있는 `StratisBitcoinFullNode` 프로젝트를 예를 들어 설명드리겠습니다.

소스코드는 https://github.com/stratisproject/StratisBitcoinFullNode 여기에서 받으시면 되고,

열어보는 것은 `src`폴더에 있는 `Stratis.Bitcoin.FullNode.sln` 로 오픈 가능할거예요 : )
